AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for timeticker'
Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Parameters:
  "Environment":
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prod"
  "Log1Url":
    Type: String
    Description: "Log1 URL"

Resources:
  ProjectUpdateTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: !Sub
          - 'TaskTickerDataTable-${Env}'
          - Env: !Ref Environment
        DeletionProtectionEnabled: true
        AttributeDefinitions:
            -
              AttributeName: week_day
              AttributeType: S
        KeySchema:
            -
              AttributeName: week_day
              KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  ChannelMappingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'TaskTickerChannelMapping-${Env}'
        - Env: !Ref Environment
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: channel_id
          AttributeType: S
      KeySchema:
        - AttributeName: channel_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TaskTickerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: taskticker/
      Handler: main.lambda_handler
      Runtime: python3.9
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectUpdateTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ChannelMappingTable
        - SSMParameterReadPolicy:
            ParameterName: taskticker-*
      Environment:
        Variables:
          ENV: !Ref Environment
          DB_TABLE_NAME: !Ref ProjectUpdateTable
          CHANNEL_MAPPING_TABLE_NAME: !Ref ChannelMappingTable
          LOG1_URL: !Ref Log1Url
      Architectures:
        - x86_64
      Events:
        mainApi:
          Type: Api
          Properties:
            Path: /app
            Method: post
        crudEvent:
          Type: Schedule
          Properties:
            State: ENABLED
            Schedule: 'cron(0 12 * * ? *)' # UTC 12:00 & IST 17:30
            Description: Daily Update Schedule
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requirement-layer
      Description: Lambda layer with libs like pocket and datetime
      ContentUri: ./libs

Outputs:
  TaskTickerApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/app
