on:
  push :
    branches:
      - main
jobs:
  buid-depoy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - run: sam build --use-container
      - run: sam deploy --stack-name taskticker --capabilities CAPABILITY_IAM --region ap-south-1 --no-confirm-changeset --no-fail-on-empty-changeset --resolve-s3 --parameter-overrides Environment='prod' Log1Url='https://api.log1.com/api'